WITH CTE AS (
    SELECT I.ANIMAL_ID,
        I.NAME
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O ON (I.ANIMAL_ID = O.ANIMAL_ID)
    ORDER BY O.DATETIME - I.DATETIME DESC
)

SELECT ANIMAL_ID,
    NAME
FROM CTE
WHERE ROWNUM <= 2