WITH CNT_WRITER AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
)

SELECT W.WRITER_ID,
    U.NICKNAME,
    U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 AS "전체주소",
    SUBSTR(U.TLNO, 0, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8, 4) AS "전화번호"
FROM CNT_WRITER W
JOIN USED_GOODS_USER U ON (W.WRITER_ID = U.USER_ID)
ORDER BY U.USER_ID DESC