SELECT
    EXTRACT(YEAR FROM S.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH,
    U.GENDER,
    COUNT(DISTINCT(S.USER_ID)) AS USERS
FROM ONLINE_SALE S
JOIN USER_INFO U ON (S.USER_ID = U.USER_ID)
WHERE U.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM S.SALES_DATE), EXTRACT(MONTH FROM S.SALES_DATE), U.GENDER
ORDER BY YEAR ASC, MONTH ASC, U.GENDER ASC