WITH USER_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE EXTRACT(YEAR FROM JOINED) = 2021
    GROUP BY USER_ID
) 

SELECT EXTRACT(YEAR FROM S.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT(S.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(S.USER_ID)) / (SELECT COUNT(USER_ID) FROM USER_2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_2021 U ON (S.USER_ID = U.USER_ID)
GROUP BY EXTRACT(YEAR FROM S.SALES_DATE),
    EXTRACT(MONTH FROM S.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC