WITH TRUCK AS (
    SELECT CAR_ID,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
), HISTORY AS (
    SELECT HISTORY_ID,
        CAR_ID,
        END_DATE - START_DATE + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
), PLAN AS (
    SELECT TO_NUMBER(RTRIM(DURATION_TYPE, '일 이상')) AS STD,
        1 - DISCOUNT_RATE / 100 AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

SELECT H.HISTORY_ID,
    ROUND(H.DURATION * T.DAILY_FEE * NVL((
        SELECT RATE
        FROM (
            SELECT 
                RATE
            FROM PLAN
            WHERE H.DURATION >= STD
            ORDER BY STD DESC
        )
        WHERE ROWNUM = 1
    ), 1)) AS FEE
FROM HISTORY H
JOIN TRUCK T ON (H.CAR_ID = T.CAR_ID)
ORDER BY FEE DESC, HISTORY_ID DESC