WITH FRONTEND AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (SELECT 1 FROM FRONTEND F WHERE D.SKILL_CODE & F.CODE != 0)
ORDER BY D.ID ASC