WITH MEMBER_CNT AS (
    SELECT R.MEMBER_ID,
        P.MEMBER_NAME,
        COUNT(R.MEMBER_ID) AS CNT
    FROM REST_REVIEW R
    JOIN MEMBER_PROFILE P ON (R.MEMBER_ID = P.MEMBER_ID)
    GROUP BY R.MEMBER_ID, P.MEMBER_NAME
    ORDER BY CNT DESC
) 

SELECT M.MEMBER_NAME,
    R.REVIEW_TEXT,
    TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN (
    SELECT MEMBER_ID, 
        MEMBER_NAME 
    FROM MEMBER_CNT 
    WHERE CNT = (SELECT MAX(CNT) FROM MEMBER_CNT)
) M ON (R.MEMBER_ID = M.MEMBER_ID)
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC