SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM (SELECT T.ITEM_ID
        FROM ITEM_TREE T
        JOIN ITEM_INFO I ON (T.PARENT_ITEM_ID = I.ITEM_ID)
        WHERE I.RARITY = 'RARE') T
JOIN ITEM_INFO I ON (T.ITEM_ID = I.ITEM_ID)
ORDER BY T.ITEM_ID DESC