SELECT DY.YEAR,
    (DY.MAX_SIZE - D.SIZE_OF_COLONY) AS YEAR_DEV,
    D.ID
FROM ECOLI_DATA D
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE,
        YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) DY ON (YEAR(D.DIFFERENTIATION_DATE) = DY.YEAR)
ORDER BY YEAR ASC, YEAR_DEV ASC