SELECT I.ID, 
    N.FISH_NAME, 
    T.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON (I.FISH_TYPE = N.FISH_TYPE)
JOIN (
    SELECT FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) T ON (I.FISH_TYPE = T.FISH_TYPE)
WHERE I.LENGTH = T.LENGTH
ORDER BY I.ID ASC