WITH AVG_DEPT AS (
    SELECT DEPT_ID,
        ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT HR.DEPT_ID,
    HR.DEPT_NAME_EN,
    AV.AVG_SAL
FROM HR_DEPARTMENT HR
JOIN AVG_DEPT AV ON (HR.DEPT_ID = AV.DEPT_ID)
ORDER BY AV.AVG_SAL DESC