SELECT F.CATEGORY,
    F.PRICE AS MAX_PRICE,
    F.PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE F.CATEGORY IN ('과자', '국', '김치', '식용유')
AND F.PRICE = (
    SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT FF
    WHERE F.CATEGORY = FF.CATEGORY
)
ORDER BY MAX_PRICE DESC